language: node_js
dist: focal
services: docker
node_js:
  - 16
before_install: 
 - chmod +x ./scripts/*.sh
install: 
 - ./scripts/install.sh
script: 
 - ./scripts/package.sh
 - travis_wait ./scripts/deploy.sh